# Generated by Django 3.1.3 on 2020-11-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red_social', '0005_auto_20201124_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='to_post',
        ),
    ]
