# Generated by Django 3.1.3 on 2020-11-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_social', '0008_auto_20201127_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='media'),
        ),
    ]
